// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwAjv0bhU-u5cUnH0wz3DAqf83T6kI2tU',
    appId: '1:952309797234:web:3f0e97b5027e933e174deb',
    messagingSenderId: '952309797234',
    projectId: 'chatappmessenger-c26bf',
    authDomain: 'chatappmessenger-c26bf.firebaseapp.com',
    storageBucket: 'chatappmessenger-c26bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOmo-JWarjlnmQPkehR7tR1cpE3KCkJiw',
    appId: '1:952309797234:android:0e86fe987b453fb3174deb',
    messagingSenderId: '952309797234',
    projectId: 'chatappmessenger-c26bf',
    storageBucket: 'chatappmessenger-c26bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjUZwJ8m_Hg2khhh9VxC_ziFGMYACl4ug',
    appId: '1:952309797234:ios:8c946cf7c832fc5c174deb',
    messagingSenderId: '952309797234',
    projectId: 'chatappmessenger-c26bf',
    storageBucket: 'chatappmessenger-c26bf.appspot.com',
    iosClientId: '952309797234-pr6dks96nhfgfm4u7e85amdnp0104t98.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjUZwJ8m_Hg2khhh9VxC_ziFGMYACl4ug',
    appId: '1:952309797234:ios:8c946cf7c832fc5c174deb',
    messagingSenderId: '952309797234',
    projectId: 'chatappmessenger-c26bf',
    storageBucket: 'chatappmessenger-c26bf.appspot.com',
    iosClientId: '952309797234-pr6dks96nhfgfm4u7e85amdnp0104t98.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessenger',
  );
}
